### ISSUE TITLE
Error messages and high CPU usage if started as background process

### ISSUE THREAD

**Issue by klausdorer** [magmaOffenburg/magmaFatProxy#3]
When starting the magmaFatProxy as background process in a bash console, it repeatedly prints error messages and consumes high amounts of CPU.

How to reproduce:
run proxy with
../magmaFatProxy/start.sh localhost 3100 3120 &

Observerd behavior:
error message on console
```
Command "null" unknown!
Known commands:
q; quit --> exit proxy server application
l; list --> list active agent proxy instances
v; verbose --> list active agent proxy instances verbosely
s; status --> print proxy status
m; --> print start of all client messages
n; --> print start of all server messages
```

Except for the null this is what we print, if someone hits a key that is not mapped.
It does not help to redirect stdin to /dev/null.

**Comment by hannesbraun** [comment]
The observed behavior (`Command "null" unknown!`) is caused by redirecting /dev/null to stdin. If nothing is redirected to stdin, reading from stdin will effectively not be possible so the process receives SIGTTIN. This causes the process to stop. With the magmaProxy 2.1.4 update (d18aa1e0c0467c623654b5467bf9c31e9e442ad6), you need to pass `--daemon` as a command line parameter to disable the command line interface in order to make magmaFatProxy work in the background.
